# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "What is Eclipse Keyple®"
  url = "/what-is-keyple/"
  weight = 10

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "Overview"
  url = "/what-is-keyple/overview/"
  weight = 10

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "Why trust Eclipse Keyple®?"
  url = "/what-is-keyple/why-trust/"
  weight = 20

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "Who is it for?"
  url = "/what-is-keyple/who-is-it-for/"
  weight = 30

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "Who is using Eclipse Keyple®?"
  url = "#adopters"
  weight = 40

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "What is Calypso®?"
  url = "/what-is-keyple/what-is-calypso/"
  weight = 50

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "Keyple's main features"
  url = "/what-is-keyple/main-features/"
  weight = 60

[[main]]
  parent = "What is Eclipse Keyple®"
  name = "News"
  url = "#news"
  weight = 70

[[main]]
  name = "Learn"
  url = "/learn/overview"
  weight = 20

[[main]]
  name = "Components"
  url = "/components/"
  weight = 30

[[main]]
  parent = "Components"
  name = "Java implementation v2+"
  url = "/components-java/overview/"
  weight = 10

[[main]]
  parent = "Components"
  name = "C++ implementation v2+"
  url = "/components-cpp/overview/"
  weight = 20

[[main]]
  parent = "Components"
  name = " "
  url = ""
  weight = 25

[[main]]
  parent = "Components"
  name = "Java implementation v1.0 (deprecated)"
  url = "/components-java-1.0/"
  weight = 30

[[main]]
  parent = "Components"
  name = "C++ implementation v0.9 (deprecated)"
  url = "/components-cpp-0.9/"
  weight = 40

[[main]]
  name = "Community"
  url = "/community/"
  weight = 40
  
[[main]]
  parent = "Community"
  name = "Contributing"
  url = "/community/contributing/"
  weight = 10
    
[[main]]
  parent = "Community"
  name = "Roadmap"
  url = "/community/roadmap/"
  weight = 20

[[main]]
  parent = "Community"
  name = "Continuous integration dashboard"
  url = "https://ci.eclipse.org/keyple/job/Keyple/"
  weight = 30

[[main]]
  parent = "Community"
  name = "Code quality dashboard"
  url = "https://sonarcloud.io/organizations/eclipse/projects?search=keyple&sort=-analysis_date"
  weight = 40

[[main]]
  parent = "Community"
  name = "Eclipse Foundation Keyple page"
  url = "https://projects.eclipse.org/projects/iot.keyple/"
  weight = 50

[[main]]
  parent = "Community"
  name = "Mailing list"
  url = "https://accounts.eclipse.org/mailing-list/keyple-dev/"
  weight = 60

[[main]]
  parent = "Community"
  name = "GitHub home repository"
  url = "https://github.com/eclipse/keyple/"
  weight = 70

[[main]]
  name = "External resources"
  url = "/external-resources/"
  weight = 50

[[main]]
  parent = "External resources"
  name = "External add-ons"
  url = "/external-resources/external-add-ons/"
  weight = 10

[[main]]
  parent = "External resources"
  name = "Compliant terminals"
  url = "/external-resources/compliant-terminals/"
  weight = 20

[[main]]
  parent = "External resources"
  name = "Support & training companies"
  url = "/external-resources/support-and-training-companies/"
  weight = 30